### ISSUE TITLE
Material design?

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/paper-toggle-button#13]
It seems that the Toggle in Android L / Material Design looks completely different. Any plans to adjust this component to match material design?

**Comment by techniq** [comment]
Angular's material switch has been updated with [new look](https://material.angularjs.org/#/demo/material.components.switch).  Here's the [source](https://github.com/angular/material/tree/master/src/components/switch).

**Comment by frankiefu** [comment]
We have also updated in master branch https://github.com/Polymer/paper-toggle-button/commit/abebce9093f7a26e4757d34b3a861728d7f23dc7.  Will be in the next release 0.5.3

**Comment by techniq** [comment]
:+1:
