### ISSUE TITLE
Third consecutive mouse drag prevented

### ISSUE THREAD

**Issue by WrinklyNinja** [Polymer/paper-toggle-button#14]
A toggle button can be toggled indefinitely by clicking on it, but if it is toggled by clicking and dragging with the mouse from
1. Off -> On
2. On -> Off

then trying to click and drag the toggle from Off to On again will cause the toggle button to move slightly, but then be prevented, and the cursor to be styled as `not-allowed`. Clicking anywhere on the page will then allow the toggle to be dragged across again.

Getting the toggle to be prevented dragging from On to Off is possible too, but reproducibility is more difficult.

This can be replicated on the [demo page](https://www.polymer-project.org/components/paper-toggle-button/demo.html) using Chrome 40.0.2214.94 m (64-bit). I can't replicate it using Firefox 35.0.1 or on Chrome for Android 40.0.2214.89 (but that's with touch rather than a mouse, so that may make a difference).

**Comment by Ortham** [comment]
Closing this as it's obsolete.
